[package]
name = "cvtree-cli"
description = "Command line interface for cvtree"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "cvtree"
path = "src/main.rs"

[dependencies]
cvtree = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }
clap = { version = "4.6.6", features = ["derive"] }
axum = "0.8.9"
tower-http = { version = "0.7.0", features = ["cors"] }
